<template>
  <div class="app-container dashboard">
    <BreadcrumbContent>
      <ul>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
        <li>qwewq</li>
      </ul>
    </BreadcrumbContent>
  </div>
</template>

<script>
import BreadcrumbContent from '@/components/BreadcrumbContent'
export default {
  components: { BreadcrumbContent },
}
</script>

<style lang="scss" scoped>
.dashboard {
  width: 100%;
  height: 100%;
}
</style>